# Generated by Django 4.1.1 on 2022-09-17 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('ticker', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sector', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('employees_count', models.IntegerField()),
                ('sic_np', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=200)),
                ('exchange_id', models.IntegerField()),
                ('cik_no', models.IntegerField()),
                ('cusip', models.CharField(max_length=25)),
                ('currency_id', models.IntegerField()),
                ('data_source_id', models.IntegerField()),
                ('ckr_log', models.BooleanField()),
                ('similar_fund_log', models.BooleanField()),
                ('address', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=25)),
                ('phone_no', models.PositiveIntegerField()),
                ('website', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('url_slug', models.CharField(max_length=25)),
                ('delisted_date', models.DateField()),
                ('delisted_reason', models.DateField()),
                ('image_name', models.ImageField(upload_to='')),
                ('image_aspect_ratio', models.IntegerField()),
                ('cumulative_return_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='daily_returns',
            fields=[
                ('date', models.IntegerField()),
                ('returns', models.IntegerField()),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('adj_close', models.IntegerField()),
                ('equity_id', models.ForeignKey(primary_key=True, on_delete=django.db.models.deletion.CASCADE, to='Backend_SQLite.equity')),
            ],
        ),
    ]
