# Generated by Django 4.1.1 on 2022-09-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_SQLite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='image_name',
            field=models.ImageField(upload_to=''),
        ),
    ]
