from django.db import models

# Create your models here.

class equity(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=25)
    ticker = models.CharField(max_length=25)
    description = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()
    sector = models.CharField(max_length=50)
    industry = models.CharField(max_length=50)
    employees_count = models.IntegerField() 
    sic_np = models.CharField(max_length=25)
    location = models.CharField(max_length=200)
    exchange_id = models.IntegerField()
    cik_no = models.IntegerField()
    cusip = models.CharField(max_length=25)
    currency_id = models.IntegerField()
    data_source_id = models.IntegerField()
    ckr_log = models.BooleanField()
    similar_fund_log = models.BooleanField()
    address = models.CharField(max_length=200)
    company_name = models.CharField(max_length=25)
    phone_no = models.PositiveIntegerField()
    website = models.CharField(max_length=50) 
    is_active = models.BooleanField()
    url_slug = models.CharField(max_length=25)
    delisted_date = models.DateField()
    delisted_reason = models.DateField()
    image_name = models.ImageField()
    image_aspect_ratio = models.IntegerField()
    cumulative_return_update = models.DateTimeField()

class equity(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=25)
    ticker = models.CharField(max_length=25)
    description = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()
    sector = models.CharField(max_length=50)
    industry = models.CharField(max_length=50)
    employees_count = models.IntegerField() 
    sic_np = models.CharField(max_length=25)
    location = models.CharField(max_length=200)
    exchange_id = models.IntegerField()
    cik_no = models.IntegerField()
    cusip = models.CharField(max_length=25)
    currency_id = models.IntegerField()
    data_source_id = models.IntegerField()
    ckr_log = models.BooleanField()
    similar_fund_log = models.BooleanField()
    address = models.CharField(max_length=200)
    company_name = models.CharField(max_length=25)
    phone_no = models.PositiveIntegerField()
    website = models.CharField(max_length=50) 
    is_active = models.BooleanField()
    url_slug = models.CharField(max_length=25)
    delisted_date = models.DateField()
    delisted_reason = models.DateField()
    image_name = models.ImageField()
    image_aspect_ratio = models.IntegerField()
    cumulative_return_update = models.DateTimeField()

class daily_returns(models.Model):
    date = models.DateField()	
    returns	= models.IntegerField()
    open = models.IntegerField()	
    high = models.IntegerField()	
    low = models.IntegerField()
    close = models.IntegerField()	
    adj_close = models.IntegerField()